### ISSUE TITLE
usb_repeat_times value in usb_hotplug test

### ISSUE THREAD

**Issue by rayx** [autotest/tp-qemu#1518]
(This is mostly a question. I'm curious how the test behaves on x86.)

The usb_repeat_times parameter in usb_hotplug test is set to 5000. An iteration (pluging device, verifying it, then unpluging it) on my aarch64 server takes about 20 seconds. So the total time will be 100000 seconds (that is, 27.8 hours). That seems ridiculously long to me. Why does the test need to be repeated so many times? How much time does it take on x86? Thanks for any information.

**Comment by vivianQizhu** [comment]
----- Original Message -----
> From: "Huan Xiong" <notifications@github.com>
> To: "autotest/tp-qemu" <tp-qemu@noreply.github.com>
> Cc: "Subscribed" <subscribed@noreply.github.com>
> Sent: Monday, October 22, 2018 2:27:36 PM
> Subject: [autotest/tp-qemu] usb_repeat_times value in usb_hotplug test (#1518)
> 
> (This is mostly a question. I'm curious how the test behaves on x86.)
> 
> The usb_repeat_times parameter in usb_hotplug test is set to 5000. An
> iteration (pluging device, verifying it, then unpluging it) on my aarch64
> server takes about 20 seconds. So the total time will be 10000 seconds (that
> is, 166 hours). That seems ridiculously long to me. Why does the test need
> to be repeated so many times? How much time does it take on x86? Thanks for
> any information.
> 

That sometimes even takes longer on x86, like 30s, so we actually set usb_repeat_times to 50 when we test it. I suppose we can actually modify the default value from 5000 to 50. Thanks.

**Comment by rayx** [comment]
Thanks for the information. I have no more question. I'll leave the issue open just in case you or someone else wants to implement the change. Otherwise feel free to close it.

**Comment by vivianQizhu** [comment]
https://github.com/autotest/tp-qemu/pull/1601
