### ISSUE TITLE
two more issues with usb test

### ISSUE THREAD

**Issue by rayx** [autotest/tp-qemu#1522]
I hit the following test issues on aarch64. I think they are perhaps common on all archs.

**Issue 1) usb_audio tests fail with usb-ehci controller, with this error:**

<pre><code>
speed mismatch trying to attach usb device "QEMU USB Audio Interface" (full speed) to bus "usbtest.0", port "2" (high speed)
</code></pre>

I think the error is as expected because, unlike other EHCI controllers (e.g., ich9-ehci), usb-ehci emulation doesn't create companion OHCI and UHCI controllers and hence support only USB 2.0 high speed. I haven't tried it yet, but I guess ich9-ehci doesn't have this issue.

I fix the issue by modifying usb.cfg:

<pre><code>
                    - usb_audio:
                        no Host_RHEL.m6
                        no Host_RHEL.m7
                        only usb_boot, usb_reboot, usb_hotplug
+                       no usb-ehci
                        usb_type = usb-audio
                        info_usb_name = "QEMU USB Audio"
                        vendor_id = "46F4"
                        product_id = "0002"
                        vendor = ""
                        product = "QEMU USB Audio"
</code></pre>
 
**Issue 2) the expected error message in usb_host negative test doesn't match the actual one on my test system.**

Take type_specific.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.usb_nodev.without_usb_hub.usb-ehci test as an example. The actual error message is:

<pre><code>
'usb-host' is not a valid device model name
</code></pre>

which makes sense to me. But the test definition in usb.cfg doesn't expect it. 

I fix the issue by modifying usb.cfg:

<pre><code>
                            - usb_negative_test:
                                usb_negative_test = "yes"
                                usb_reply_msg = "Property 'usb-host.productid' doesn't take value"
                                Host_RHEL.m6:
                                    # Now no output from monitor for negative test on Host_RHEL.m6
                                    usb_reply_msg = ""
                                Host_RHEL.m7:
                                    usb_reply_msg = "Parameter 'productid' expects an int64 value or range;"
                                    usb_reply_msg += "Parameter 'vendorid' expects an int64 value or range;"
                                    usb_reply_msg += "productid out of range;"
                                    usb_reply_msg += "vendorid out of range;"
                                    usb_reply_msg += "Parameter 'productid' expects uint32_t;"
                                    usb_reply_msg += "Parameter 'vendorid' expects uint32_t;"
+                               arm64-pci, arm64-mmio:
+                                   usb_reply_msg = "'usb-host' is not a valid device model name"
                                usb_host_device_list = "aaa:aaa,aaa:111,21231:11231333,11231333:21231,21231:1123132233,2123133:1123132233111,1123132233111:111"
</code></pre>

The change is specific to aarch64, though I suspect x86 may have the same issue.

**Comment by vivianQizhu** [comment]
@rayx Thanks for the experiment.
For the first issue, It looks you are not using the newest tp-qemu for your test, without below commit:
```
commit 396888c6928f00a60b421b4cde8f6e1629b56e1d
Author: qizhu <qizhu@redhat.com>
Date:   Mon Aug 6 11:03:05 2018 +0800

    usb: disable usb_audio test for all RHEL Host per not supported
    
    Signed-off-by: qizhu <qizhu@redhat.com>
```
Which I disable usb_audio test for all RHEL host, since qemu doesn't support it.

For the second issue, x86 actually passed on usb-host..usb_negative_test. So firstly this should be an arm specific issue.
And you also miss below commit, If you are testing on RHEL8 host, it might helps.
```
commit b63cb9caf2c09d801476820be7803c99e3b54074
Author: qizhu <qizhu@redhat.com>
Date:   Mon Aug 6 14:47:27 2018 +0800

    usb: Extend default usb_reply_msg for RHEL8 and later qemu
    
    Signed-off-by: qizhu <qizhu@redhat.com>
```
But per the error message you provided, seems arm64-pci has not `usb-host` device supported, so I suspect can other `usb_host` tests pass on arm? If not, I will suggest disable all `usb_host` for arm.

**Comment by vivianQizhu** [comment]
Besides, FYI, during my recent test on x86, I have all usb_hotplug..usb_ccid test failed. Other usb cases mostly work well.

**Comment by rayx** [comment]
@vivianQizhu Regarding the first issue, my qemu test contains that commit. It doesn't work for me probably because my test system runs Centos (does avocado consider it as RHEL?). BTW, it's possible to configure VM to plug a usb-audio device. One approach is using qemu-xhci. This works out of box because qemu-xhci has built-in support for all speeds. Another approach (see its [doc](https://github.com/qemu/qemu/blob/master/docs/usb2.txt) and [example](https://github.com/qemu/qemu/blob/master/docs/config/ich9-ehci-uhci.cfg)) is using ich9-usb-ehci1 and ich9-usb-uhci1. The former supports high speed, and the latter low and full speed. The trick is that user needs to explicitly specify ich9-usb-uhci1 as a companion on CLI (I misunderstood this in my original report). Also user needs to make sure usb-audio is plugged into the right port. I verified both approaches on my test system. So I'll ignore this issue.
Regarding the second issue, I didn't know usb-host is a valid device. I had thought it's a random string for negative test. It's not available on my host perhaps because I didn't enable it while compiling qemu. I'll take a closer look and update the issue later.

**Comment by rayx** [comment]
FYI. hotplug.*ccid tests (to save time, I only ran them with qemu-xhci controller) work fine on my aarch64 test system. I observed other test failures, but none seems to be related to qemu.

**Comment by vivianQizhu** [comment]
> @vivianQizhu Regarding the first issue, my qemu test contains that commit. It doesn't work for me probably because my test system runs Centos (does avocado consider it as RHEL?). 

I am not sure about this.

>BTW, it's possible to configure VM to plug a usb-audio device. 

That's not about the configuration, RHEL has no this device supported in its qemu binary(check the output of # qemu-kvm -device ?)
While your solution to add `no usb-ehci` is okay for me, if you do have usb-audio device in your qemu binary.

> Regarding the second issue, I didn't know usb-host is a valid device. I had thought it's a random string for negative test. It's not available on my host perhaps because I didn't enable it while compiling qemu. I'll take a closer look and update the issue later.
You can also check it by # qemu-kvm -device ?
Should be able to find this: `name "usb-host", bus usb-bus`, under: `Controller/Bridge/Hub devices:` if your qemu support this device.

**Comment by rayx** [comment]
Thanks. I have figured out the reason. The usb-host device depends on libusb library, which wasn't installed on my system when I compiled qemu.
