### ISSUE TITLE
pci_hotplug: "blk_virtio_blk" test failed, and it should

### ISSUE THREAD

**Issue by rayx** [autotest/tp-qemu#1569]
I tried this hotplug test and it failed:

  type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_block.blk_virtio_blk.with_reboot 

The test generated this command line:

<pre><code>
MALLOC_PERTURB_=1  /usr/bin/qemu-system-aarch64 \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox off  \
    -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
    -drive file=/var/lib/avocado/data/avocado-vt/images/jeos-27-aarch64_AAVMF_VARS.fd,if=pflash,format=raw,unit=1 \
    -machine virt,gic-version=host  \
    -nodefaults  \
    -vga none  \
    -chardev socket,id=hmp_id_qmpmonitor1,path=/var/tmp/avocado_iDoB2t/monitor-qmpmonitor1-20181116-133923-dyiBdMJy,server,nowait \
    -mon chardev=hmp_id_qmpmonitor1,mode=readline  \
    -chardev socket,id=hmp_id_catch_monitor,path=/var/tmp/avocado_iDoB2t/monitor-catch_monitor-20181116-133923-dyiBdMJy,server,nowait \
    -mon chardev=hmp_id_catch_monitor,mode=readline  \
    -serial unix:'/var/tmp/avocado_iDoB2t/serial-serial0-20181116-133923-dyiBdMJy',server,nowait \
    -device qemu-xhci,id=usb1, bus=pcie.0,addr=0x1 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pcie.0,addr=0x2 \
    -drive id=drive_image1,if=none,format=qcow2,file=/var/lib/avocado/data/avocado-vt/images/jeos-27-aarch64.qcow2 \
    -device scsi-hd,id=image1,drive=drive_image1 \
    -device virtio-net-pci,mac=9a:55:56:57:58:59,rombar=0,id=idO6zg9g,vectors=4,netdev=idi3Azb6,bus=pcie.0,addr=0x3   \
    -m 1024  \
    -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  \
    -cpu 'host' \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  \
    -vnc :0  \
    -rtc base=utc,clock=host \
    -enable-kvm
</code></pre>

It failed when trying to hotplug a virtio-blk-pci device, using this command:

<pre><code>
device_add  id=block-idQsbTry,driver=virtio-blk-pci,drive=block-idQsbTry
</code></pre>

The error message was:

<pre><code>
Bus 'pcie.0' does not support hotplugging
</code></pre>

The error seems reasonable to me. Note that virtio-blk-pci is a PCI device. Because the device_add command doesn't specify bus to plug the device into, QEMU tries to look for a PCI bus in the VM and find pcie.0, which is the PCIe root bus and the only PCI bus in the VM set up with the above command line. But PCIe root bus is implemented as having no hotplug support in QEMU, and hence the error.

Does this test work on x86 (say, Q35)? I doubt it.

**Comment by vivianQizhu** [comment]
@rayx pci_hotplug does not support q35, or pcie. Actually all pci_* test cases aims to pci bus, include pci_devices. They might fit to pcie as well after some adjustment, but most of them should not support pcie so far. I am not sure but in the further this series of test even might be removed from tp-qemu.

**Comment by rayx** [comment]
Thanks for the information. It's good to know it's OK to skip them. BTW, for pcie, I think devices can be plugged into root port or switch down stream port, but that requires to change test script to add them ahead.

**Comment by vivianQizhu** [comment]
@rayx You are right, pcie devices can be ho tplugged to pcie-root-port under pcie.0, and pci devices can be hot plugged into pci bridge. We include the hot plug tests in different features, and support pcie hotplug with vm.devices.simple_hotplug(). So where we use vm.devices.simple_hotplug(), that is pcie supported.

**Comment by rayx** [comment]
So I did a search for simple_hotplug in tp-qemu code and found block_hotplug.py uses it. I'll give that test a try. Thanks!
