### ISSUE TITLE
Migrate tp-qemu to travis-ci.com

### ISSUE THREAD

**Issue by luckyh** [autotest/tp-qemu#2876]
Since June 15th, 2021, the building on travis-ci.org is ceased. Therefore we need to migrate the repo to travis-ci.com for re-enabling the check.

Hi @clebergnu,
as my github account does not have the permisson for doing so, would you mind to help perform the migration? Thanks in advance!

**Comment by PaulYuuu** [comment]
Hello @ana , do you plan to fix this issue on tp-qemu like tp-libvirt as well?

**Comment by ana** [comment]
> Hello @ana , do you plan to fix this issue on tp-qemu like tp-libvirt as well?

Done! Please check https://github.com/autotest/tp-qemu/pull/2913

**Comment by PaulYuuu** [comment]
> > Hello @ana , do you plan to fix this issue on tp-qemu like tp-libvirt as well?
> 
> Done! Please check #2913

Wow, thank you so much for your quick fix, it is really useful for us!
